name: CI
on:
  repository_dispatch:
    types: [storage-blobcreated]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Check variables
      env:
        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload.data) }}
      run: |
          echo  "${{ toJson(github.event.client_payload.eventType) }}"
          echo  "${{ toJson(github.event.client_payload.data.contentType) }}"
          echo  "${{ github.event.client_payload.data.contentType }}"


